# Generated by Django 6.0.1 on 2026-02-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('advisor_id', models.CharField(db_column='AdvisorID', max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, db_column='FullName', max_length=255, null=True)),
                ('type_english', models.CharField(blank=True, db_column='Type_English', max_length=50, null=True)),
                ('full_name_english', models.CharField(blank=True, db_column='FullName_English', max_length=255, null=True)),
                ('position_advisor', models.CharField(blank=True, db_column='Position_Advisor', max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, db_column='Nickname', max_length=100, null=True)),
                ('research_title', models.TextField(blank=True, db_column='ResearchTitle', null=True)),
                ('major', models.CharField(blank=True, db_column='Major', max_length=100, null=True)),
                ('faculty', models.CharField(blank=True, db_column='Faculty', max_length=50, null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('expertise', models.TextField(blank=True, db_column='Expertise', null=True)),
                ('date_time', models.DateTimeField(blank=True, db_column='Date_Time', null=True)),
            ],
            options={
                'db_table': 'Advisors',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(db_column='CompanyID', max_length=50, primary_key=True, serialize=False)),
                ('product', models.TextField(blank=True, db_column='Product', null=True)),
                ('company_detail', models.TextField(blank=True, db_column='Company_Detail', null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='DocumentRepository',
            fields=[
                ('doc_id', models.CharField(db_column='DocID', max_length=50, primary_key=True, serialize=False)),
                ('doc_name', models.CharField(db_column='DocName', max_length=255)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('file_link', models.TextField(db_column='File_Link')),
            ],
            options={
                'db_table': 'Document_Repository',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(db_column='EmployeeID', max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, db_column='FullName', max_length=255, null=True)),
                ('position', models.CharField(blank=True, db_column='Position', max_length=100, null=True)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=50, null=True)),
                ('permission', models.CharField(blank=True, db_column='Permission', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('entrepreneur_id', models.AutoField(db_column='EntrepreneurID', primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, db_column='Business_Name', max_length=255, null=True)),
                ('fullname', models.CharField(blank=True, db_column='Fullname', max_length=255, null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Entrepreneur',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.CharField(db_column='FacilityID', max_length=50, primary_key=True, serialize=False)),
                ('facility_name', models.CharField(db_column='FacilityName', max_length=255)),
                ('facility_type', models.CharField(blank=True, db_column='FacilityType', max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
                ('location', models.TextField(blank=True, db_column='Location', null=True)),
                ('status', models.CharField(db_column='Status', default='Available', max_length=20)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('photo', models.TextField(blank=True, db_column='Photo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At')),
            ],
            options={
                'db_table': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_name', models.CharField(db_column='FacultyName', max_length=100, primary_key=True, serialize=False)),
                ('number_code', models.CharField(blank=True, db_column='NumberCode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.CharField(db_column='UserID', max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, db_column='FullName', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('permission', models.CharField(blank=True, db_column='Permission', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(db_column='ProjectID', max_length=50, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, db_column='ProjectName', max_length=255, null=True)),
                ('project_fullname', models.TextField(blank=True, db_column='ProjectFullname', null=True)),
                ('project_detail', models.TextField(blank=True, db_column='ProjectDetail', null=True)),
                ('date_time', models.DateTimeField(blank=True, db_column='Date_Time', null=True)),
                ('create_by', models.CharField(blank=True, db_column='Create_By', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectAward',
            fields=[
                ('paid', models.CharField(db_column='PAID', max_length=50, primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, db_column='TeamName', max_length=50, null=True)),
                ('project_name', models.CharField(blank=True, db_column='ProjectName', max_length=50, null=True)),
                ('around', models.CharField(blank=True, db_column='Around', max_length=50, null=True)),
                ('year', models.CharField(blank=True, db_column='Year', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Project_Award',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(db_column='StudentID', max_length=50, primary_key=True, serialize=False)),
                ('type_student', models.CharField(blank=True, db_column='Type_Student', max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, db_column='FullName', max_length=255, null=True)),
                ('type_student_english', models.CharField(blank=True, db_column='Type_Student_English', max_length=50, null=True)),
                ('full_name_english', models.CharField(blank=True, db_column='FullName_English', max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, db_column='Nickname', max_length=100, null=True)),
                ('major', models.CharField(blank=True, db_column='Major', max_length=100, null=True)),
                ('faculty', models.CharField(blank=True, db_column='Faculty', max_length=50, null=True)),
                ('year_of_study', models.CharField(blank=True, db_column='Year_of_Study', max_length=50, null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('date_time', models.DateTimeField(blank=True, db_column='Date_Time', null=True)),
                ('create_by', models.CharField(blank=True, db_column='Create_By', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(db_column='TeamID', max_length=50, primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, db_column='TeamName', max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, db_column='ProjectName', max_length=50, null=True)),
                ('date_time', models.DateTimeField(blank=True, db_column='Date_Time', null=True)),
            ],
            options={
                'db_table': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.CharField(db_column='TrainingID', max_length=50, primary_key=True, serialize=False)),
                ('training_name', models.CharField(blank=True, db_column='TrainingName', max_length=255, null=True)),
                ('training_date', models.DateField(blank=True, db_column='TrainingDate', null=True)),
            ],
            options={
                'db_table': 'Training',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(db_column='BookingID', max_length=50, primary_key=True, serialize=False)),
                ('booking_date', models.DateField(blank=True, db_column='BookingDate', null=True)),
                ('start_time', models.TimeField(blank=True, db_column='StartTime', null=True)),
                ('end_time', models.TimeField(blank=True, db_column='EndTime', null=True)),
                ('topic', models.CharField(blank=True, db_column='Topic', max_length=255, null=True)),
                ('status', models.CharField(db_column='Status', default='Pending', max_length=20)),
                ('facility', models.ForeignKey(blank=True, db_column='FacilityID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.facility')),
                ('booked_by_user', models.ForeignKey(blank=True, db_column='BookedBy_UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.login')),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('request_id', models.CharField(db_column='RequestID', max_length=50, primary_key=True, serialize=False)),
                ('issue_title', models.CharField(blank=True, db_column='Issue_Title', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('status', models.CharField(db_column='Status', default='New', max_length=20)),
                ('facility', models.ForeignKey(blank=True, db_column='FacilityID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.facility')),
                ('requester', models.ForeignKey(blank=True, db_column='RequesterID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.login')),
            ],
            options={
                'db_table': 'Maintenance_Requests',
            },
        ),
    ]
