# Generated by Django 6.0.1 on 2026-02-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_name', models.CharField(db_column='BankName', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.AutoField(db_column='ContestID', primary_key=True, serialize=False)),
                ('contest_name', models.CharField(blank=True, db_column='ContestName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Contest',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('researcher_id', models.CharField(db_column='ResearcherID', max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, db_column='FullName', max_length=255, null=True)),
                ('expertise', models.TextField(blank=True, db_column='Expertise_Researcher', null=True)),
            ],
            options={
                'db_table': 'Researcher',
            },
        ),
        migrations.CreateModel(
            name='ResearcherProject',
            fields=[
                ('res_proj_id', models.AutoField(db_column='ResProjID', primary_key=True, serialize=False)),
                ('researcher_id', models.CharField(blank=True, db_column='ResearcherID', max_length=50, null=True)),
                ('project_name', models.CharField(blank=True, db_column='ProjectName', max_length=255, null=True)),
                ('year', models.CharField(blank=True, db_column='Year', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Researcher_Project',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('speaker_id', models.CharField(db_column='SpeakerID', max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, db_column='FullName', max_length=255, null=True)),
                ('expertise', models.TextField(blank=True, db_column='Expertise', null=True)),
            ],
            options={
                'db_table': 'Speaker',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('barcode', models.CharField(db_column='Barcode', max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('total_stock', models.IntegerField(blank=True, db_column='Total_Stock', null=True)),
            ],
            options={
                'db_table': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='StudentAdvisor',
            fields=[
                ('stad_id', models.CharField(db_column='STADID', max_length=50, primary_key=True, serialize=False)),
                ('student', models.CharField(blank=True, db_column='StudentID', max_length=50, null=True)),
                ('advisor', models.CharField(blank=True, db_column='AdvisorID', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Student_Advisors',
            },
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('spid', models.CharField(db_column='SPID', max_length=50, primary_key=True, serialize=False)),
                ('student', models.CharField(blank=True, db_column='StudentID', max_length=50, null=True)),
                ('project_name', models.CharField(blank=True, db_column='ProjectName', max_length=255, null=True)),
                ('year', models.CharField(blank=True, db_column='Year', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Student_Project',
            },
        ),
        migrations.CreateModel(
            name='TeamAdvisor',
            fields=[
                ('taid', models.CharField(db_column='TAID', max_length=50, primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, db_column='TeamName', max_length=255, null=True)),
                ('advisor', models.CharField(blank=True, db_column='AdvisorID', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Team_Advisors',
            },
        ),
        migrations.CreateModel(
            name='TeamProject',
            fields=[
                ('tpid', models.CharField(db_column='TPID', max_length=50, primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, db_column='TeamName', max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, db_column='ProjectName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Team_Projects',
            },
        ),
        migrations.CreateModel(
            name='TeamStudent',
            fields=[
                ('tsid', models.CharField(db_column='TSID', max_length=50, primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, db_column='TeamName', max_length=255, null=True)),
                ('student', models.CharField(blank=True, db_column='StudentID', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Team_Student',
            },
        ),
    ]
