# Generated by Django 6.0.1 on 2026-02-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bank_contest_researcher_researcherproject_speaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='floor',
            field=models.IntegerField(blank=True, db_column='Floor', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='zone',
            field=models.CharField(blank=True, db_column='Zone', max_length=10, null=True),
        ),
    ]
