# Generated by Django 6.0.1 on 2026-02-03 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facility_floor_facility_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTimeline',
            fields=[
                ('timeline_id', models.AutoField(primary_key=True, serialize=False)),
                ('milestone_title', models.CharField(max_length=255)),
                ('milestone_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='core.project')),
            ],
            options={
                'db_table': 'ProjectTimeline',
                'ordering': ['milestone_date'],
            },
        ),
    ]
