# Generated by Django 6.0.1 on 2026-02-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projecttimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttimeline',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='timeline_evidence/'),
        ),
    ]
