# Generated by Django 6.0.1 on 2026-02-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projecttimeline_evidence_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, db_column='PhoneNumber', max_length=20, null=True),
        ),
    ]
