# Generated by Django 6.0.1 on 2026-02-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, db_column='UserID', max_length=50, null=True)),
                ('action', models.CharField(db_column='Action', max_length=50)),
                ('model_name', models.CharField(db_column='ModelName', max_length=50)),
                ('object_id', models.CharField(blank=True, db_column='ObjectID', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='Timestamp')),
                ('details', models.TextField(blank=True, db_column='Details', null=True)),
            ],
            options={
                'db_table': 'Audit_Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EntrepreneurIncome',
            fields=[
                ('ei_id', models.AutoField(primary_key=True, serialize=False)),
                ('entrepreneur_id', models.CharField(blank=True, db_column='EntrepreneurID', max_length=50, null=True)),
                ('year', models.CharField(blank=True, db_column='Year', max_length=20, null=True)),
                ('income', models.DecimalField(blank=True, db_column='Income', decimal_places=2, max_digits=12, null=True)),
                ('details', models.TextField(blank=True, db_column='Details', null=True)),
            ],
            options={
                'db_table': 'EntrepreneurIncome',
            },
        ),
        migrations.CreateModel(
            name='SpeakerTraining',
            fields=[
                ('spt_id', models.AutoField(primary_key=True, serialize=False)),
                ('speaker_id', models.CharField(blank=True, db_column='SpeakerID', max_length=50, null=True)),
                ('training_id', models.CharField(blank=True, db_column='TrainingID', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Speaker_Training',
            },
        ),
        migrations.CreateModel(
            name='StudentAward',
            fields=[
                ('said', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.CharField(blank=True, db_column='StudentID', max_length=50, null=True)),
                ('award_name', models.CharField(blank=True, db_column='AwardName', max_length=255, null=True)),
                ('around', models.CharField(blank=True, db_column='Around', max_length=50, null=True)),
                ('year', models.CharField(blank=True, db_column='Year', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Student_Award',
            },
        ),
        migrations.CreateModel(
            name='StudentTraining',
            fields=[
                ('stid', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.CharField(blank=True, db_column='StudentID', max_length=50, null=True)),
                ('training_id', models.CharField(blank=True, db_column='TrainingID', max_length=50, null=True)),
                ('status', models.CharField(db_column='Status', default='Registered', max_length=50)),
            ],
            options={
                'db_table': 'Student_Training',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='budget_year',
            field=models.CharField(blank=True, db_column='BudgetYear', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.TextField(blank=True, db_column='Objective', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='concept',
            field=models.TextField(blank=True, db_column='Concept', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='development_needs',
            field=models.TextField(blank=True, db_column='DevelopmentNeeds', null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='project_link',
            field=models.CharField(blank=True, db_column='ProjectLink', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('sm_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(db_column='Qty')),
                ('action_type', models.CharField(db_column='ActionType', max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True, db_column='Date_Time')),
                ('user', models.CharField(blank=True, db_column='UserID', max_length=50, null=True)),
                ('stock_item', models.ForeignKey(db_column='StockID', on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
            options={
                'db_table': 'Stock_Movement',
            },
        ),
    ]
