# Generated by Django 6.0.1 on 2026-02-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog_entrepreneurincome_speakertraining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaward',
            name='award_name',
            field=models.CharField(blank=True, db_column='AwardName', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='rank',
            field=models.CharField(blank=True, db_column='Rank', max_length=50, null=True),
        ),
    ]
