# Generated by Django 6.0.1 on 2026-02-06 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_projectaward_award_name_projectaward_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='project_link',
        ),
        migrations.AddField(
            model_name='training',
            name='lecturer_name',
            field=models.CharField(blank=True, db_column='LecturerName', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='project',
            field=models.ForeignKey(blank=True, db_column='ProjectID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='core.project'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_end_date',
            field=models.DateField(blank=True, db_column='TrainingEndDate', null=True),
        ),
    ]
