# Generated by Django 6.0.1 on 2026-02-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_training_project_link_training_lecturer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttraining',
            name='training_id',
        ),
        migrations.AddField(
            model_name='studenttraining',
            name='training',
            field=models.ForeignKey(db_column='TrainingID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.training'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studenttraining',
            name='student',
            field=models.ForeignKey(db_column='StudentID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='core.student'),
            preserve_default=False,
        ),
    ]
