# Generated by Django 6.0.1 on 2026-02-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_studenttraining_training_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studenttraining',
            unique_together={('student', 'training')},
        ),
    ]
