# Generated by Django 6.0.1 on 2026-02-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_studenttraining_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='registrant_name',
            field=models.CharField(blank=True, db_column='RegistrantName', max_length=255, null=True),
        ),
    ]
